name: 'AWS IaC using Terraform'

#on:
#  push:
#    branchesname: Terraform AWS Deployment

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      action:
        description: "Select Action"
        required: true
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format 
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

      # Runs automatically on every push
      - name: Terraform Plan
        if: github.event_name == 'push'
        run: terraform plan

      # Runs only when "apply" is selected
      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve

      # Runs only when "destroy" is selected
      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve
